apiVersion: apps/v1
kind: Deployment
metadata:
  name: kifta
  namespace: default
  labels:
    app: kifta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kifta
  template:
    metadata:
      labels:
        app: kifta
    spec:
      containers:
      - name: etcd
        image: docker.pkg.github.com/the-mikedavis/kifta/etcd:v1
        ports:
        - containerPort: 2379
          name: data
        - containerPort: 2380
          name: host
      - name: kube-apiserver
        image: docker.pkg.github.com/the-mikedavis/kifta/kube-apiserver:v1
        ports:
        - containerPort: 6443
          name: api
      - name: kube-controller-manager
        image: docker.pkg.github.com/the-mikedavis/kifta/kube-controller-manager:v1
        ports:
        - containerPort: 10257
          name: api
      - name: kube-scheduler
        image: docker.pkg.github.com/the-mikedavis/kifta/kube-scheduler:v1
        ports:
        - containerPort: 10251
          name: api
