apiVersion: v1
kind: EncryptionConfig
resources:
- resources:
    - secrets
  providers:
    # by providing this item in the list first, data encryption at rest is
    # disabled
    - identity: {}
    - aescbc:
        keys:
          - name: key1
            secret: SuCpkrdWhuiJo002FWfM5lknnEtjs3o44L4ulSUHOk8=
